DEF_DIFF_STATUS(OK,                                     "OK")

DEF_DIFF_STATUS(ERROR_EXPR_TREE_ERROR,                  "EXPR_TREE_ERROR")

DEF_DIFF_STATUS(ERROR_MEM_ALLOC,                        "ERROR_MEM_ALLOC")

DEF_DIFF_STATUS(ERROR_REC_FALL,                         "ERROR_REC_FALL")

DEF_DIFF_STATUS(ERROR_PREV_TEX_NOT_ENDED_YET,           "ERROR_PREV_TEX_NOT_ENDED_YET")

DEF_DIFF_STATUS(ERROR_NO_TEX_FILE_STARTED,              "ERROR_NO_TEX_FILE_STARTED")

DEF_DIFF_STATUS(ERROR_CANT_CREATE_TEX_FOLDER,           "ERROR_CANT_CREATE_TEX_FOLDER")

DEF_DIFF_STATUS(ERROR_CANT_CREATE_TEX_FILE,             "ERROR_CANT_CREATE_TEX_FILE")

DEF_DIFF_STATUS(ERROR_TOKEN_PARSING,                    "ERROR_TOKEN_PARSING")
